### ISSUE TITLE
"cmp" function should either be documented or removed from the API

### ISSUE THREAD

**Issue by rydrman** [python-semver/python-semver#117]
This function is part of the documentation and public API but is undocumented and looks a little like an alias to `compare`, though it is very much not. I'm simply suggesting that it become `_cmp` or get a useful docstring.

**Comment by doransmestad** [comment]
Just got burned by this.  Was using `cmp` when I should have been using `compare`.   If anyone else runs into an issue where semver comparison isn't working correctly, check that you're using the `compare` function before doing much else debugging.   

The current documentation makes it seem like these two functions are the same because of the visual proximity:  

![image](https://user-images.githubusercontent.com/8120019/55434071-beeffc00-5564-11e9-9219-cdd1373bf78f.png)

I haven't looked into the code to tell what the difference between the two are, but perhaps simply removing `cmp` from the docs will discourage its use?

**Comment by tomschr** [comment]
Thanks @rydrman @doransmestad for the repot and hints.

A (limited) docstring is available in master now, see https://github.com/python-semver/python-semver/blob/master/semver.py#L27

> I haven't looked into the code to tell what the difference between the two are, but perhaps simply removing cmp from the docs will discourage its use?

Acutally, it's coming from Python2 which has a `cmp` function, but Python3 removed this. So this is just bringing it back. However, I agree, it could be documented better.

Currently it acts as a helper function for the `VersionInfo.compare` function. Maybe we should better make it "private" by adding a "_" prefix for `cmp` (=> `_cmp`).

**Comment by tomschr** [comment]
> perhaps simply removing cmp from the docs will discourage its use?

Yes, I think that is the way to go. 

I've merged #242 lately which also has an impact on Sphinx. There, I didn't include `semver.cmp` as it gives too much confusion. Actually, I consider it as an implementation detail.

Use the official section [Comparing Versions](https://python-semver.readthedocs.io/en/latest/usage.html#comparing-versions) in our documentation.

I think, we can close this issue for the time being. If you still have the feeling there is something missing, reopen it and we can discuss it.

Thanks! :+1:
