### ISSUE TITLE
Rename VersionInfo to Version

### ISSUE THREAD

**Issue by tlaferriere** [python-semver/python-semver#305]
>So there are my two suggestions for this issue:
> * Overload the constructor with `__init__(self, version: str)`
> * __Rename `VersionInfo` to `Version`__

_Originally posted by @tlaferriere in https://github.com/python-semver/python-semver/issues/258#issuecomment-648810597_

Just addressing this explicitly

**Comment by tomschr** [comment]
Thanks for opening this. :+1: 

I think, this issue is closely related to #303. In this issue, I present the idea of an (overloaded) `semver.version` function which acts as a wrapper for all different types. So I guess, we have a third option here which we should discuss. :wink: 

Regardless of the constructor/initializer or the `semver.version` function, renaming VersionInfo to Version is okay to me as long as we have an alias (something like `VersionInfo = Version` which also outputs a deprecation warning when used).
