### ISSUE TITLE
Semver breaks on additional installation of conan and artifactory

### ISSUE THREAD

**Issue by dnns92** [python-semver/python-semver#394]
# Situation

When using a blank environment with a 
~~~bash
pip install semver==2.13.0
python3 -c "import semver;semver.VersionInfo"
~~~

This will work. When I install conan==1.59.0 and dohq-artifactory==0.8.4 on top, this will break the semver and lead to an error after calling `python3 -c "import semver;semver.VersionInfo"`
~~~bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'semver' has no attribute 'VersionInfo'
~~~

# To Reproduce

Tested on Ubuntu20.04
~~~bash
python3 -m venv venv  && source venv/bin/activate
pip install semver==2.13.0
python3 -c "import semver;semver.VersionInfo"  # no error
pip install conan==1.59.0 dohq-artifactory==0.8.4
python3 -c "import semver;semver.VersionInfo"  # error printed above
~~~

# Expected Behavior

No error

# Environment
- OS: Ubuntu 20.04 LTS
- Python version 3.8
- Version of semver library 2.13.0

# Additional context

**Comment by dnns92** [comment]
This is related to node-semver, a dependecy of conan. Therefore, one will never be able to run conan and this package in the same venv. I dont want to stick my nose into stuff I don't know enough about, but there are a couple of packages named semver, like also the one named here:  #381. Maybe calling this package python_semver or similar is more future-proof.

**Comment by tomschr** [comment]
Thanks @dnns92 for your report, much appreciated.

I've tried to replicate it and it looks like it's issue #259. It's a name clash.

If you list your packages you get:

```
$ pip list
node-semver        0.6.1
[...]
semver             2.13.0
```

If you look closer in your Python environment, you will see these files and directories:

```
$ ls -ld .env/lib/python3.10/site-packages/semver*
.env/lib/python3.10/site-packages/semver
.env/lib/python3.10/site-packages/semver-2.13.0.dist-info
.env/lib/python3.10/site-packages/semver.py
```

In other words, there is a file `semver.py` which comes from this project. But at the same time, there is a directory `semver` which comes from the `node-semver` project. It seems, the latter takes precedence over the former. That's why you see this error as the `node-semver` doesn't provide a `VersionInfo` class.

Unfortunately, PyPI does not prevent from uploading a project which contains an already existing module/package.

I fear, this is something hard to solve. Renaming this project would break a lot of existing projects. If you know an idea to solve this, I'm open for your suggestion.

At the moment, `semver` and `node-semver` cannot be used at the same time.

**Comment by tomschr** [comment]
> Maybe calling this package python_semver or similar is more future-proof.

Thanks, that's what I also though about, but I think it would be a bad idea.

Renaming this project will break a lot of existing projects that depends on `semver`. According to the [semver's dependency list](https://github.com/python-semver/python-semver/network/dependents), there are over >23.500 repositories(!) that uses this project.

Whereas at the same time [node-semver's dependencies](https://github.com/podhmo/python-node-semver/network/dependents) lists >800 repos.

Forcing all 23.500 maintainers to use a different name would have a huge impact and wouldn't make these project maintainers very happy. Even if we file issues to notify of the rename, it's unrealistic and a huge task. Apart

I'm not even sure, if we can demand a rename from node-semver project (although the impact would be less than for this project).

So, not sure how to handle this... :shrug:

**Comment by alexandrevicenzi** [comment]
The package node-semver was already renamed, see https://github.com/podhmo/python-node-semver/issues/39.

It will be in 0.9.0 release, see https://github.com/podhmo/python-node-semver/issues/45.

Conan will need to update their dependency to not clash with this package.

**Comment by tomschr** [comment]
@dnns92 Thanks for all your comments.

I've looked a bit closer and it seems the other project is already aware of this problem and has issue podhmo/python-node-semver#39. Additionally they work on a new release, see podhmo/python-node-semver#45. Unfortunately, it's not yet released.

To solve this is to use the new name `nodesemver` instead of `semver` once they released it.

Maybe ask in the python-node-semver project when they will release the new version?

**Comment by tomschr** [comment]
In the light of a new release for python-node-semver, I think this project can't do much. There is already a solution work in progress, although not yet released.

As such, I think it doesn't make sense to have this issue open. Closing it for the time being.

Many thanks for your contribution!
